openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: Manage tasks with API

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean

paths:
  /tasks:
    get:
      summary: Get tasks list
      responses:
        '200':
          description: List tasks
          content:
            application/json:
              schema:
                type: array
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    delete:
      summary: Delete multiple tasks
      requestBody:
        required: true
        content:
          apschema:
            type: array
            items:
              $ref: '#/components/schemas/Task'

      responses:
        '200':
          description: Task list deleted
          content:
            aschema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
