openapi: 3.0.0
info:
  title: User Profile API
  version: 1.0.0
  description: API for managing user profiles

components:
  schemas:
    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birthdate:
          type: string
          format: date

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        country:
          type: string
        postal_code:
          type: integer

paths:
  /users/{id}:
    get:
      summary: Récupérer un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: object

  /users:
    post:
      summary: Create multiple user profiles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
      responses:
        '201':
          description: Users created
          content:
            application/json:
              schema:
                type: array

  /users/{id}/personalInfo:
    put:
      summary: Update personal information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
             type: object
      responses:
        '200':
          description: Personal information updated
          content:
            application/json:
              schema:
                type: object

  /users/{id}/address:
    put:
      summary: Update address
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
             type: object
      responses:
        '200':
          description: Address updated
          content:
            application/json:
              schema:
               type: object

  /users/{id}/preferences:
    put:
      summary: Update user preferences
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
             type: object
      responses:
        '200':
          description: Preferences updated
          content:
            application/json:
              schema:
               type: object